### PR TITLE
Switch from google calendar to tui calendar

### PR DESCRIPTION
**Pull request by kelseygonzalez**

### CODE REVIEW

**Comment by kelseygonzalez** [comment]
switch from google calendar to tui calendar. I have **not** previewed locally to make sure it looks right, so if you want to run jekyll before accepting PR go for it.

**Comment by kelseygonzalez** [comment]
tagging @alex-r-bigelow and @zoidy since I'm not a maintainer in this repo!

**Comment by alex-r-bigelow** [comment]
This looks cool!

It looks like the colors / typography got lost from the google doc?

In case it helps, the rest of the page uses Roboto Slab, and [here's a color swatch](https://colordesigner.io/#235387-EA5A2A-F0BCAB-C9DAF8-4A525A) based on the other colors already in use

**Comment by kelseygonzalez** [comment]
I can implement that @alex-r-bigelow ! Let me make the changes [in the source](https://github.com/kelseygonzalez/resbaz2021schedule/blob/main/index.html). speaking of that, how's your javascript? This is made with [tui calendar](https://github.com/nhn/tui.calendar) which [has a way to hide weekends](https://nhn.github.io/tui.calendar/latest/tutorial-example07-hide-weekends) but I can't get the option to work because this (which was made using an API for it) is set up a little bit different. No pressure, but if you could figure it out I'd be grateful!

**Comment by zoidy** [comment]
@kelseygonzalez Cool looking calendar! If I can make a small suggestion, I'd recommend not including the entire source code for the library. It'd be better to include the script from their CDN. I can take a crack at figuring out the weekday thing.

**Comment by zoidy** [comment]
Ok, pull request created. It worked locally for me so hopefully it will work on the site

**Comment by kelseygonzalez** [comment]
I love the idea of not adding all of the library source code! As I said, I used an API to create this version and get kind of lost scrolling to see what's what (besides the part at the bottom with the workshops). However, @zoidy , I don't see a PR anywhere. Can you link to it here?

**Comment by kelseygonzalez** [comment]
@zoidy I think I see it - you forked my repo and just haven't made the PR yet. Keep in touch! I'd love to get this figured out (and especially removing the weekends, like I mentioned above!)

**Comment by zoidy** [comment]
> @zoidy I think I see it - you forked my repo and just haven't made the PR yet. Keep in touch! I'd love to get this figured out (and especially removing the weekends, like I mentioned above!)

Here's the pull request. https://github.com/kelseygonzalez/resbaz2021schedule/pull/1

That's cool that there's a way to generate the calendar. Mind linking to it? I'm all for low-code solutions!

**Comment by kelseygonzalez** [comment]
Not sure why I wasn't notified of this message or the PR you sent, but I just merged them in! My goodness I'm so happy with how much better it looks @zoidy . It's such an improvement! Thanks so much.

**Pull request merged**
