### PR TITLE
WIP explorations into an interactive schedule

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
Currently just a map; will transition into more of a "who has what expertise, and what breakout sessions are going on?" online-only thing in the coming weeks

### CODE REVIEW

**Comment by alex-r-bigelow** [comment]
@julianpistorius, do we have any plans for how registration will work? If we did a google form, it would be cool for people to check boxes about their own expertise, and optionally choose to make their information public so that people could orchestrate their own breakout sessions in a way that other participants could find relevant ones?

Could also be fun / easy to make summary charts for showing "how many people here (across the event / inside a zoom chat) are comfortable with git?"

**Comment by alex-r-bigelow** [comment]
Probably too much to do before May, but it could be really cool to connect registration info with [zoom's API](https://marketplace.zoom.us/docs/api-reference/zoom-api/dashboards/dashboardmeetingparticipants) (to do things like "how comfortable is my audience with git?")

**Comment by julianpistorius** [comment]
Hi @alex-r-bigelow! Sorry I just saw this. 

Very cool idea, but I guess we're not doing Catalyst now.

I don't know what the current plan for registrations is.

**Comment by alex-r-bigelow** [comment]
No worries, I mostly submitted this per a request that the code be saved in case it's wanted for replication next year; I'll close it for now (I think you answered my registration question a while ago on Slack)

**Pull request closed without merging**
