### PR TITLE
Add 2022 stub page

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
(Also remove shut up and write logo)

### CODE REVIEW

**Comment by alex-r-bigelow** [comment]
@Gchism94 I don't think I have admin privileges to add you, but here's at least the stub for the webpage (yes, we know this thing is ancient + messy + needs a pretty major update)

**Comment by alex-r-bigelow** [comment]
@zoidy, thanks for updating this—looks like we both did stuff at the same time.

Maybe we should use PRs going forward?

**Comment by zoidy** [comment]
Apologies, I was working in response to a request and hadn't noticed you had a PR. I don't believe PR's had been used much in this repo but I'm happy to work within that framework.

**Review by zoidy — APPROVED** [review]

**Comment by alex-r-bigelow** [comment]
Thanks, @zoidy!

**Pull request merged**
